# File: package.yaml

name:                payment-engine
version:             0.1.0.0
# Optional: fill these in
# github:              "github.com/RatnakirtiKamble/FlowPay"
# author:              "Ratnakirti Kamble"
# maintainer:          "ratnakirti1234@gmail.com"
# copyright:           "2025 Your Name"


dependencies:
  - base >=4.16 && <4.19
  - servant
  - servant-server
  - warp
  - aeson
  - text
  - bytestring
  - postgresql-simple
  - mtl
  - time
  - wai
  - bcrypt
  - cookie
  - servant-auth-server
  - wai-extra
  - jose-jwt
  - jose
  - crypton
  - base64-bytestring
  - wai-cors >= 0.2.7
  - http-types
  - monad-logger
  - dotenv >= 0.7


executables:
  payment-engine-exe:
    main:                Main.hs
    source-dirs:
      - src
      - app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N